- id: '1741304812655'
  alias: Doorbell detected a person or package
  description: Doorbell detected a person or package
  triggers:
  - entity_id:
    - binary_sensor.g4_doorbell_pro_person_detected
    - binary_sensor.g4_doorbell_pro_package_detected
    to: 'on'
    trigger: state
  conditions:
  - condition: time
    before: '19:30:00'
    after: 07:30:00
  actions:
  - data:
      target:
      - media_player.living_room_echo
      - media_player.basement_echo
      - media_player.basement_dot
      - media_player.loft_dot
      - media_player.bedroom_dot
      - media_player.gym_dot
      message: <audio src='https://raw.githubusercontent.com/jasonsmith425/stuff/refs/heads/master/chime.mp3'/>
      data:
        type: tts
    action: notify.alexa_media
  - delay:
      seconds: 2.5
  - data:
      target:
      - media_player.living_room_echo
      - media_player.basement_echo
      - media_player.basement_dot
      - media_player.loft_dot
      - media_player.bedroom_dot
      - media_player.gym_dot
      data:
        type: tts
      message: There is a person or package at the door
    action: notify.alexa_media
  mode: single
- id: '1741565365390'
  alias: Doorbell button pressed
  description: Somebody pressed the doorbell button
  triggers:
  - entity_id:
    - sensor.g4_doorbell_pro_last_doorbell_ring
    trigger: state
  conditions:
  actions:
  - data:
      target:
      - media_player.living_room_echo
      - media_player.basement_echo
      - media_player.basement_dot
      - media_player.loft_dot
      - media_player.bedroom_dot
      - media_player.gym_dot
      message: <audio src='https://raw.githubusercontent.com/jasonsmith425/stuff/refs/heads/master/chime.mp3'/>
      data:
        type: tts
    action: notify.alexa_media
  - delay:
      seconds: 2.5
  - data:
      target:
      - media_player.living_room_echo
      - media_player.basement_echo
      - media_player.basement_dot
      - media_player.loft_dot
      - media_player.bedroom_dot
      - media_player.gym_dot
      data:
        type: tts
      message: Somebody rang the doorbell
    action: notify.alexa_media
  mode: single
- id: '1748235641762'
  alias: little one
  description: ''
  triggers:
  - trigger: conversation
    command: little one
  conditions: []
  actions:
  - action: notify.alexa_media
    metadata: {}
    data:
      message: <audio src='https://raw.githubusercontent.com/jasonsmith425/stuff/refs/heads/master/littleone.mp3'/>
      target:
      - media_player.elara_dot
      data:
        type: tts
  mode: single
- id: '1748236016673'
  alias: mountains
  description: ''
  triggers:
  - trigger: conversation
    command:
    - mountains
  conditions: []
  actions:
  - action: notify.alexa_media
    metadata: {}
    data:
      message: <audio src='https://raw.githubusercontent.com/jasonsmith425/stuff/refs/heads/master/mountains.mp3'/>
      target:
      - media_player.elara_dot
      data:
        type: tts
  mode: single
- id: '1748236087442'
  alias: wheels
  description: ''
  triggers:
  - trigger: conversation
    command:
    - wheels on the bus
  conditions: []
  actions:
  - action: notify.alexa_media
    metadata: {}
    data:
      message: <audio src='https://raw.githubusercontent.com/jasonsmith425/stuff/refs/heads/master/wheels.mp3'/>
      target:
      - media_player.elara_dot
      data:
        type: tts
  mode: single
- id: '1748236230456'
  alias: stop elara dot
  description: ''
  triggers:
  - trigger: conversation
    command:
    - stop elara dot
  conditions: []
  actions:
  - action: notify.alexa_media
    metadata: {}
    data:
      target:
      - media_player.elara_dot
      data:
        type: tts
      message: ' '
  mode: single
- id: '1748291918744'
  alias: apt
  description: ''
  triggers:
  - trigger: conversation
    command:
    - apt
  conditions: []
  actions:
  - action: notify.alexa_media
    metadata: {}
    data:
      message: <audio src='https://raw.githubusercontent.com/jasonsmith425/stuff/refs/heads/master/apt.mp3'/>
      target:
      - media_player.elara_dot
      data:
        type: tts
  mode: single
